# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qud_explorer_window.ui',
# licensing of 'qud_explorer_window.ui' applies.
#
# Created: Sun Sep 15 18:44:01 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tile_label = QtWidgets.QLabel(self.centralwidget)
        self.tile_label.setMinimumSize(QtCore.QSize(160, 240))
        self.tile_label.setStyleSheet("background-color: rgb(15, 59, 58);")
        self.tile_label.setText("")
        self.tile_label.setObjectName("tile_label")
        self.verticalLayout_4.addWidget(self.tile_label)
        self.save_tile_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_tile_button.setObjectName("save_tile_button")
        self.verticalLayout_4.addWidget(self.save_tile_button)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_label = QtWidgets.QLabel(self.centralwidget)
        self.search_label.setObjectName("search_label")
        self.horizontalLayout_2.addWidget(self.search_label)
        self.search_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line_edit.setObjectName("search_line_edit")
        self.horizontalLayout_2.addWidget(self.search_line_edit)
        self.expand_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.expand_all_button.setObjectName("expand_all_button")
        self.horizontalLayout_2.addWidget(self.expand_all_button)
        self.collapse_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.collapse_all_button.setObjectName("collapse_all_button")
        self.horizontalLayout_2.addWidget(self.collapse_all_button)
        self.restore_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.restore_all_button.setObjectName("restore_all_button")
        self.horizontalLayout_2.addWidget(self.restore_all_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tree_target_widget = QtWidgets.QWidget(self.centralwidget)
        self.tree_target_widget.setObjectName("tree_target_widget")
        self.verticalLayout_3.addWidget(self.tree_target_widget)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuWiki = QtWidgets.QMenu(self.menubar)
        self.menuWiki.setObjectName("menuWiki")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_ObjectBlueprints_xml = QtWidgets.QAction(MainWindow)
        self.actionOpen_ObjectBlueprints_xml.setObjectName("actionOpen_ObjectBlueprints_xml")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionWiki_template = QtWidgets.QAction(MainWindow)
        self.actionWiki_template.setCheckable(True)
        self.actionWiki_template.setChecked(True)
        self.actionWiki_template.setObjectName("actionWiki_template")
        self.actionAttributes = QtWidgets.QAction(MainWindow)
        self.actionAttributes.setCheckable(True)
        self.actionAttributes.setObjectName("actionAttributes")
        self.actionAll_attributes = QtWidgets.QAction(MainWindow)
        self.actionAll_attributes.setCheckable(True)
        self.actionAll_attributes.setObjectName("actionAll_attributes")
        self.actionScan_wiki = QtWidgets.QAction(MainWindow)
        self.actionScan_wiki.setObjectName("actionScan_wiki")
        self.actionUpload_templates = QtWidgets.QAction(MainWindow)
        self.actionUpload_templates.setObjectName("actionUpload_templates")
        self.actionUpload_tiles = QtWidgets.QAction(MainWindow)
        self.actionUpload_tiles.setObjectName("actionUpload_tiles")
        self.actionXML_source = QtWidgets.QAction(MainWindow)
        self.actionXML_source.setCheckable(True)
        self.actionXML_source.setObjectName("actionXML_source")
        self.actionShow_help = QtWidgets.QAction(MainWindow)
        self.actionShow_help.setObjectName("actionShow_help")
        self.menuFile.addAction(self.actionOpen_ObjectBlueprints_xml)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionWiki_template)
        self.menuView.addAction(self.actionAttributes)
        self.menuView.addAction(self.actionAll_attributes)
        self.menuView.addAction(self.actionXML_source)
        self.menuWiki.addAction(self.actionScan_wiki)
        self.menuWiki.addAction(self.actionUpload_templates)
        self.menuWiki.addAction(self.actionUpload_tiles)
        self.menuHelp.addAction(self.actionShow_help)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWiki.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Qud Blueprint Explorer", None, -1))
        self.save_tile_button.setText(QtWidgets.QApplication.translate("MainWindow", "Save tile...", None, -1))
        self.search_label.setText(QtWidgets.QApplication.translate("MainWindow", "Search:", None, -1))
        self.expand_all_button.setText(QtWidgets.QApplication.translate("MainWindow", "Expand all", None, -1))
        self.collapse_all_button.setText(QtWidgets.QApplication.translate("MainWindow", "Collapse all", None, -1))
        self.restore_all_button.setText(QtWidgets.QApplication.translate("MainWindow", "Default expansion", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View type", None, -1))
        self.menuWiki.setTitle(QtWidgets.QApplication.translate("MainWindow", "Wiki", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionOpen_ObjectBlueprints_xml.setText(QtWidgets.QApplication.translate("MainWindow", "Open ObjectBlueprints.xml...", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionWiki_template.setText(QtWidgets.QApplication.translate("MainWindow", "Wiki template", None, -1))
        self.actionAttributes.setText(QtWidgets.QApplication.translate("MainWindow", "Attributes", None, -1))
        self.actionAll_attributes.setText(QtWidgets.QApplication.translate("MainWindow", "All attributes", None, -1))
        self.actionScan_wiki.setText(QtWidgets.QApplication.translate("MainWindow", "Scan wiki for selected objects", None, -1))
        self.actionUpload_templates.setText(QtWidgets.QApplication.translate("MainWindow", "Upload templates for selected objects", None, -1))
        self.actionUpload_tiles.setText(QtWidgets.QApplication.translate("MainWindow", "Upload tiles for selected objects", None, -1))
        self.actionXML_source.setText(QtWidgets.QApplication.translate("MainWindow", "XML source", None, -1))
        self.actionShow_help.setText(QtWidgets.QApplication.translate("MainWindow", "Show help", None, -1))

